[phases.setup]
nixPkgs = ['nodejs_20', 'php83', 'php83Extensions.pdo', 'php83Extensions.pdo_mysql', 'php83Extensions.mysqli', 'php83Extensions.mbstring', 'php83Extensions.xml', 'php83Extensions.curl', 'php83Extensions.zip', 'php83Extensions.gd', 'php83Extensions.fileinfo', 'php83Packages.composer']

[phases.install]
cmds = [
    'npm ci --prefer-offline --no-audit --progress=false --maxsockets=1',
    'composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist'
]

[phases.build]
cmds = [
    "export NODE_OPTIONS='--max-old-space-size=1024'",
    "timeout 300 npm run build || timeout 180 npm run build:simple || (echo 'Build failed, creating minimal assets...' && mkdir -p public/build/assets && echo '{\"resources/js/app.jsx\":{\"file\":\"assets/app.js\",\"isEntry\":true}}' > public/build/manifest.json)"
]

[start]
cmd = 'bash start.sh'

[variables]
NODE_ENV = 'production'
VITE_APP_ENV = 'production'