[phases.setup]
nixPkgs = ['nodejs_20', 'php83', 'php83Extensions.pdo', 'php83Extensions.pdo_mysql', 'php83Extensions.mysqli', 'php83Extensions.mbstring', 'php83Extensions.xml', 'php83Extensions.curl', 'php83Extensions.zip', 'php83Extensions.gd', 'php83Extensions.fileinfo', 'php83Packages.composer']

[phases.install]
cmds = [
    'npm ci',
    'composer install --no-dev --optimize-autoloader'
]

[phases.build]
cmds = [
    'npm run build'
]

[start]
cmd = 'chmod +x start.sh && ./start.sh'